# -*- coding: utf-8 -*-
"""Categorical_Encoding.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mO4sqHGKGKgvSaA9T81A-EZUFIrGa7th
"""

# One-Hot Encoding the categorical columns and converting True/False to 0/1
df= pd.get_dummies(df, columns=['contract_status', 'subscription_combination', 'download_usage_category'], drop_first=True).astype(int)

# Check the result
print(df.head())

df.info()