# -*- coding: utf-8 -*-
"""Creating_new_features.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mO4sqHGKGKgvSaA9T81A-EZUFIrGa7th
"""

# Create contract_status Based on remaining_contract
# Create 'contract_status', label as 'long_term' if more than 1 year
df['contract_status'] = df['remaining_contract'].apply(lambda x: 'long_term' if x > 1 else 'short_term')

print(df[['remaining_contract', 'contract_status']].head())

# Create 'subscription_combination' feature, where users subscribed to both TV and movie are labeled as 'both'
df['subscription_combination'] = df.apply(lambda row: 'both' if row['is_tv_subscriber'] == 1 and row['is_movie_package_subscriber'] == 1 else 'single_or_none', axis=1)

print(df[['is_tv_subscriber', 'is_movie_package_subscriber', 'subscription_combination']].head())

import numpy as np

# Create 'download_usage_category': 'no_usage' if 'download_avg' is 0, otherwise bin into 'low', 'medium', or 'high'
df['download_usage_category'] = np.where(df['download_avg'] == 0, 'no_usage',
                                         pd.cut(df['download_avg'], bins=[0, 50, 200, 1000], labels=['low', 'medium', 'high'], include_lowest=True))

print(df[['download_avg', 'download_usage_category']].head())

# Create interaction feature 'contract_download_interaction' by calculating the product
df['contract_download_interaction'] = df['remaining_contract'] * df['download_avg']

# Check the new feature
print(df[['remaining_contract', 'download_avg', 'contract_download_interaction']].head())

df.info()