# -*- coding: utf-8 -*-
"""Dropping_unnecessary_columns.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mO4sqHGKGKgvSaA9T81A-EZUFIrGa7th
"""

# Drop the 'id' column
df = df.drop(columns=['id'])

print(df.head())