# -*- coding: utf-8 -*-
"""Feature_scaling_standardization.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mO4sqHGKGKgvSaA9T81A-EZUFIrGa7th
"""

from sklearn.preprocessing import StandardScaler

# Select the numerical columns
numerical_columns = ['subscription_age', 'bill_avg', 'remaining_contract', 'download_avg', 'upload_avg', 'service_failure_count']

# Standardize the numerical columns
scaler = StandardScaler()
df[numerical_columns] = scaler.fit_transform(df[numerical_columns])

print(df[numerical_columns].head())

df.info()