# -*- coding: utf-8 -*-
"""PCA.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mO4sqHGKGKgvSaA9T81A-EZUFIrGa7th
"""

from sklearn.decomposition import PCA
# Separate the target variable (churn) from the feature variables
X = df.drop('churn', axis=1)  # Features
y = df['churn']  # Target

# Apply PCA to reduce the dimensionality of the features, keeping 10 principal components
pca = PCA(n_components=10)
X_pca = pca.fit_transform(X)

# Convert the PCA result into a DataFrame and add the 'churn' target variable back
X_pca_df = pd.DataFrame(data=X_pca, columns=[f'Principal Component {i+1}' for i in range(10)])
X_pca_df['churn'] = y

# Check the DataFrame structure (optional)
print(X_pca_df.info())