# -*- coding: utf-8 -*-
"""Definitions_for_the_columns.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mO4sqHGKGKgvSaA9T81A-EZUFIrGa7th
"""

#Link: https://www.kaggle.com/datasets/mehmetsabrikunt/internet-service-churn/data

#id: unique subscriber id
#is_tv_subscriber: Does he/she have a tv subscription ?
#is_movie_package_subscriber: Does he/she have a sinema movie package subs?
#subscription_age: How many year has the customer use our service?
#bill_avg: Last 3 months bill avg
#eamining_contract: How many years are left on the customer's contract? If null, the customer does not have a contract. Customers with active contracts must use the service until it ends, or they will incur a penalty if they cancel early.
#service_failure_count: Customer call count to call center for service failure for last 3 months
#download_avg: Last 3 months internet usage (GB)
#upload_avg: Last 3 months upload avg (GB)
#download_over_limit: Most customers have a download limit. If they exceed it, they must pay. This column shows the 'limit over count' for the past 9 months.
#churn: This is the target column. A value of 1 indicates the customer canceled their service.