# -*- coding: utf-8 -*-
"""Heatmap.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mO4sqHGKGKgvSaA9T81A-EZUFIrGa7th
"""

#Heatmap
import matplotlib.pyplot as plt
import seaborn as sns

corr = df.corr()
cmap = sns.diverging_palette(220, 10, as_cmap=True)
sns.heatmap(
    corr,
    cmap=cmap,
    square=True,
    cbar_kws={'shrink': .9},
    ax = plt.subplots(figsize=(12,10))[1],
    annot=True,
    annot_kws={'fontsize':12}
)