# -*- coding: utf-8 -*-
"""Unassign_the_runtime_for_resetting.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mO4sqHGKGKgvSaA9T81A-EZUFIrGa7th
"""

# Unassign the runtime for resetting
from google.colab import runtime
runtime.unassign()