# -*- coding: utf-8 -*-
"""Upload_the_data.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mO4sqHGKGKgvSaA9T81A-EZUFIrGa7th
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io
filename = 'Internet_Service_Provider_Customer_Churn.csv'

global df  # Declaring the DataFrame as a global variable
df = pd.read_csv(io.BytesIO(uploaded[filename]))  # Reading the uploaded CSV into pandas

df.head()