# -*- coding: utf-8 -*-
"""OpenAI_LangChain_setup.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mO4sqHGKGKgvSaA9T81A-EZUFIrGa7th
"""

#OpenAI LangChain setup
!pip install -q openai langchain langchain-community
!pip install -q --upgrade openai

!pip show openai