# -*- coding: utf-8 -*-
"""Boxplot_for_Numerical_Variables.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mO4sqHGKGKgvSaA9T81A-EZUFIrGa7th
"""

# Boxplot for Numerical Variables
# Top correlated variable: 'remaining_contract'
plt.figure(figsize=(10, 6))
sns.boxplot(x='churn', y='remaining_contract', data=df)
plt.title('Boxplot of Remaining Contract vs Churn')
plt.show()
# Shorter contracts correlate with higher churn: Churned users typically have shorter remaining contracts.
# Outliers: Some churned users have long contracts, but they are rare.

# Another important variable: 'download_avg'
plt.figure(figsize=(10, 6))
sns.boxplot(x='churn', y='download_avg', data=df)
plt.title('Boxplot of Download Avg vs Churn')
plt.show()
#Most users have low internet usage: Both churned and non-churned users show similar low usage levels.
#Outliers exist, but no clear trend: High-usage outliers appear, but no strong correlation between usage and churn is observed.