# -*- coding: utf-8 -*-
"""Distribution_Plot_for_Numerical_Variables.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mO4sqHGKGKgvSaA9T81A-EZUFIrGa7th
"""

# Distribution Plot for Numerical Variables
# Distribution plot for 'remaining_contract', categorized by 'churn'
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='remaining_contract', hue='churn', kde=True, stat="density", common_norm=False)
plt.title('Distribution of Remaining Contract by Churn')
plt.show()
# Churned users (orange): Most have almost no remaining contract time, indicating they churn near the contract's end.
# Non-churned users (blue): Their contract lengths are more evenly distributed, suggesting less correlation between contract length and retention.

# Distribution plot for 'download_avg', categorized by 'churn'
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='download_avg', hue='churn', kde=True, stat="density", common_norm=False)
plt.title('Distribution of Download Avg by Churn')
plt.show()
# Most users (churned and non-churned) have low average internet usage, clustered near zero.
# No clear distinction between churned and non-churned users based on internet usage, as both distributions are nearly identical.