# -*- coding: utf-8 -*-
"""Stacked_Bar_Plot_for_Categorical_Variables.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mO4sqHGKGKgvSaA9T81A-EZUFIrGa7th
"""

# Stacked Bar Plot for Categorical Variables
# Stacked bar plot for 'is_tv_subscriber' to observe the churn distribution among TV subscribers
tv_subscriber_churn = pd.crosstab(df['is_tv_subscriber'], df['churn'], normalize='index')
tv_subscriber_churn.plot(kind='bar', stacked=True, figsize=(10, 6))
plt.title('Stacked Bar Plot of TV Subscriber vs Churn')
plt.ylabel('Proportion')
plt.show()
# Non-TV subscribers: Higher churn rate compared to non-churned users.
# TV subscribers: Lower churn rate with more non-churned users.
# Overall, TV subscribers are less likely to churn than non-TV subscribers.

# Stacked bar plot for 'is_movie_package_subscriber' to see if movie package subscribers are more likely to churn
movie_subscriber_churn = pd.crosstab(df['is_movie_package_subscriber'], df['churn'], normalize='index')
movie_subscriber_churn.plot(kind='bar', stacked=True, figsize=(10, 6))
plt.title('Stacked Bar Plot of Movie Package Subscriber vs Churn')
plt.ylabel('Proportion')
plt.show()
# Non-movie package subscribers: Higher churn rate with a greater proportion of churned users.
# Movie package subscribers: Lower churn rate, with more non-churned users.
# Movie package subscribers are less likely to churn than non-subscribers.