# -*- coding: utf-8 -*-
"""Scatter_plots_of_correlation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mO4sqHGKGKgvSaA9T81A-EZUFIrGa7th
"""

# Scatter plot to check the relationship between 'download_avg' and 'upload_avg'
plt.figure(figsize=(10, 6))
sns.scatterplot(x='download_avg', y='upload_avg', data=df)
plt.title('Scatter Plot of Download Avg vs Upload Avg')
plt.show()
# Low value concentration: Most users have low download and upload averages.
# Positive correlation: Higher download averages generally align with higher upload averages, though less consistent at high values.

# Scatter plot to check the relationship between 'download_avg' and 'bill_avg'
plt.figure(figsize=(10, 6))
sns.scatterplot(x='download_avg', y='bill_avg', data=df)
plt.title('Scatter Plot of Download Avg vs Bill Avg')
plt.show()
# Concentration at lower values: Most users have both low download averages and low bills, clustering in the bottom-left corner.
# Weak positive correlation: Higher downloads tend to result in higher bills, but inconsistently.