# -*- coding: utf-8 -*-
"""Split_training_and_test_sets.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mO4sqHGKGKgvSaA9T81A-EZUFIrGa7th
"""

from sklearn.model_selection import train_test_split

X = df.drop('churn', axis=1)  # Features
y = df['churn']  # Target

# Split the data into training+validation and testing sets (70% train+val, 30% test)
X_train_val, X_test, y_train_val, y_test = train_test_split(X_pca_df.drop('churn', axis=1), y, test_size=0.3, random_state=42)

# Split the training+validation set into separate training and validation sets (70% train, 30% val)
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.3, random_state=42)

display(X_train.shape)
display(X_test.shape)
display(X_val.shape)

y_val.value_counts()

y_train.value_counts()